parameters:
#    casecenter_administration.example.class: Casecenter\AdministrationBundle\Example

services:
#    casecenter_administration.example:
#        class: %casecenter_administration.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
