<?php

namespace Casecenter\PlanningBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DateRepository extends EntityRepository
{
	public function getWithBookings()
	{
		$qb = $this->createQueryBuilder('a');
		$qb->leftJoin('a.bookings', 'b')->addSelect('b');
		$qb->orderBy('a.date', 'ASC');

		return $qb->getQuery()->getResult();
	}
}
