parameters:
#    casecenter_project.example.class: Casecenter\ProjectBundle\Example

services:
#    casecenter_project.example:
#        class: %casecenter_project.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
