dashboard:
    pattern: /
    defaults: {_controller: CasecenterDashboardBundle:Default:index, name: default}

casecenter_dashboard:
    resource: "@CasecenterDashboardBundle/Resources/config/routing.yml"
    prefix:   /dashboard/

# Security Routes
login:
    pattern: /login
    defaults: {_controller: CasecenterUserBundle:Security:login}
login_check:
    pattern: /login_check
logout:
    pattern: /logout