parameters:
#    casecenter_planning.example.class: Casecenter\PlanningBundle\Example

services:
#    casecenter_planning.example:
#        class: %casecenter_planning.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
