<?php

namespace Casecenter\SupportBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FormatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormatRepository extends EntityRepository
{
	public function getWithSupportAndPage($slugSupport, $slugPage, $slugFormat)
	{
		$qb = $this->_em->createQueryBuilder();

		$qb->select('f');
		$qb->from($this->_entityName, 'f');
		$qb->innerJoin('f.page', 'p', 'WITH', 'p.slug = :slugPage')->setParameter('slugPage', $slugPage);
		$qb->addSelect('p');
		$qb->innerJoin('p.support', 's', 'WITH', 's.slug = :slugSupport')->setParameter('slugSupport', $slugSupport);
		$qb->addSelect('s');
		$qb->where('f.slug = :slug')->setParameter('slug', $slugFormat);

		try {
			return $qb->getQuery()->getSingleResult();
		} catch (\Doctrine\Orm\NoResultException $e) {return null;}
	}
}
