parameters:
#    casecenter_user.example.class: Casecenter\UserBundle\Example

services:
#    casecenter_user.example:
#        class: %casecenter_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
